# KNN

In [33]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sklearn

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score,

In [34]:
data=pd.read_csv('iris_csv.csv')
print(data.head())

   sepallength  sepalwidth  petallength  petalwidth        class
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [35]:
x=data.iloc[:,:4]
x.head()

   sepallength  sepalwidth  petallength  petalwidth
0          5.1         3.5          1.4         0.2
1          4.9         3.0          1.4         0.2
2          4.7         3.2          1.3         0.2
3          4.6         3.1          1.5         0.2
4          5.0         3.6          1.4         0.2

In [47]:
y=data.iloc[:,-1]
y.head()

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: class, dtype: object

In [36]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.20)

In [37]:
x_test

     sepallength  sepalwidth  petallength  petalwidth
53           5.5         2.3          4.0         1.3
30           4.8         3.1          1.6         0.2
82           5.8         2.7          3.9         1.2
73           6.1         2.8          4.7         1.2
43           5.0         3.5          1.6         0.6
25           5.0         3.0          1.6         0.2
27           5.2         3.5          1.5         0.2
83           6.0         2.7          5.1         1.6
129          7.2         3.0          5.8         1.6
7            5.0         3.4          1.5         0.2
109          7.2         3.6          6.1         2.5
64           5.6         2.9          3.6         1.3
46           5.1         3.8          1.6         0.2
68           6.2         2.2          4.5         1.5
80           5.5         2.4          3.8         1.1
50           7.0         3.2          4.7         1.4
116          6.5         3.0          5.5         1.8
11           4.8         3.4          1.6         0.2
126          6.2         2.8          4.8         1.8
71           6.1         2.8          4.0         1.3
16           5.4         3.9          1.3         0.4
128          6.4         2.8          5.6         2.1
117          7.7         3.8          6.7         2.2
87           6.3         2.3          4.4         1.3
133          6.3         2.8          5.1         1.5
106          4.9         2.5          4.5         1.7
90           5.5         2.6          4.4         1.2
14           5.8         4.0          1.2         0.2
74           6.4         2.9          4.3         1.3
86           6.7         3.1          4.7         1.5

In [38]:
x_train

     sepallength  sepalwidth  petallength  petalwidth
13           4.3         3.0          1.1         0.1
131          7.9         3.8          6.4         2.0
120          6.9         3.2          5.7         2.3
134          6.1         2.6          5.6         1.4
95           5.7         3.0          4.2         1.2
..           ...         ...          ...         ...
1            4.9         3.0          1.4         0.2
85           6.0         3.4          4.5         1.6
37           4.9         3.1          1.5         0.1
94           5.6         2.7          4.2         1.3
89           5.5         2.5          4.0         1.3

[120 rows x 4 columns]

In [39]:
classifier=KNeighborsClassifier(n_neighbors=5)

In [40]:
classifier.fit(x_train,y_train)

KNeighborsClassifier()

In [41]:
y_pred=classifier.predict(x_test)

In [42]:
y_pred

array(['Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor'], dtype=object)

In [43]:
y_test

53     Iris-versicolor
30         Iris-setosa
82     Iris-versicolor
73     Iris-versicolor
43         Iris-setosa
25         Iris-setosa
27         Iris-setosa
83     Iris-versicolor
129     Iris-virginica
7          Iris-setosa
109     Iris-virginica
64     Iris-versicolor
46         Iris-setosa
68     Iris-versicolor
80     Iris-versicolor
50     Iris-versicolor
116     Iris-virginica
11         Iris-setosa
126     Iris-virginica
71     Iris-versicolor
16         Iris-setosa
128     Iris-virginica
117     Iris-virginica
87     Iris-versicolor
133     Iris-virginica
106     Iris-virginica
90     Iris-versicolor
14         Iris-setosa
74     Iris-versicolor
86     Iris-versicolor
Name: class, dtype: object

In [44]:
cm=confusion_matrix(y_test,y_pred)
ac=accuracy_score(y_test,y_pred)

In [45]:
cm

array([[ 9,  0,  0],
       [ 0, 11,  2],
       [ 0,  1,  7]])

In [46]:
ac

0.9