In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.svm import SVC

In [2]:
data=pd.read_csv('iris_csv.csv')
data.head()

   sepallength  sepalwidth  petallength  petalwidth        class
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [3]:
x=data.iloc[:,:4]
x.head()

   sepallength  sepalwidth  petallength  petalwidth
0          5.1         3.5          1.4         0.2
1          4.9         3.0          1.4         0.2
2          4.7         3.2          1.3         0.2
3          4.6         3.1          1.5         0.2
4          5.0         3.6          1.4         0.2

In [4]:
y=data.iloc[:,-1]
y.head()

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: class, dtype: object

In [5]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.20)

In [6]:
x_test

     sepallength  sepalwidth  petallength  petalwidth
80           5.5         2.4          3.8         1.1
20           5.4         3.4          1.7         0.2
54           6.5         2.8          4.6         1.5
2            4.7         3.2          1.3         0.2
33           5.5         4.2          1.4         0.2
83           6.0         2.7          5.1         1.6
125          7.2         3.2          6.0         1.8
145          6.7         3.0          5.2         2.3
104          6.5         3.0          5.8         2.2
76           6.8         2.8          4.8         1.4
62           6.0         2.2          4.0         1.0
135          7.7         3.0          6.1         2.3
84           5.4         3.0          4.5         1.5
65           6.7         3.1          4.4         1.4
97           6.2         2.9          4.3         1.3
87           6.3         2.3          4.4         1.3
114          5.8         2.8          5.1         2.4
90           5.5         2.6          4.4         1.2
38           4.4         3.0          1.3         0.2
51           6.4         3.2          4.5         1.5
30           4.8         3.1          1.6         0.2
36           5.5         3.5          1.3         0.2
12           4.8         3.0          1.4         0.1
34           4.9         3.1          1.5         0.1
147          6.5         3.0          5.2         2.0
67           5.8         2.7          4.1         1.0
13           4.3         3.0          1.1         0.1
146          6.3         2.5          5.0         1.9
60           5.0         2.0          3.5         1.0
91           6.1         3.0          4.6         1.4

In [7]:
classifier=SVC(kernel='linear')

In [8]:
classifier.fit(x_train,y_train)

SVC(kernel='linear')

In [9]:
y_pred=classifier.predict(x_test)

In [10]:
x_test

     sepallength  sepalwidth  petallength  petalwidth
80           5.5         2.4          3.8         1.1
20           5.4         3.4          1.7         0.2
54           6.5         2.8          4.6         1.5
2            4.7         3.2          1.3         0.2
33           5.5         4.2          1.4         0.2
83           6.0         2.7          5.1         1.6
125          7.2         3.2          6.0         1.8
145          6.7         3.0          5.2         2.3
104          6.5         3.0          5.8         2.2
76           6.8         2.8          4.8         1.4
62           6.0         2.2          4.0         1.0
135          7.7         3.0          6.1         2.3
84           5.4         3.0          4.5         1.5
65           6.7         3.1          4.4         1.4
97           6.2         2.9          4.3         1.3
87           6.3         2.3          4.4         1.3
114          5.8         2.8          5.1         2.4
90           5.5         2.6          4.4         1.2
38           4.4         3.0          1.3         0.2
51           6.4         3.2          4.5         1.5
30           4.8         3.1          1.6         0.2
36           5.5         3.5          1.3         0.2
12           4.8         3.0          1.4         0.1
34           4.9         3.1          1.5         0.1
147          6.5         3.0          5.2         2.0
67           5.8         2.7          4.1         1.0
13           4.3         3.0          1.1         0.1
146          6.3         2.5          5.0         1.9
60           5.0         2.0          3.5         1.0
91           6.1         3.0          4.6         1.4

In [11]:
y_pred

array(['Iris-versicolor', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor'],
      dtype=object)

In [12]:
cm=confusion_matrix(y_test,y_pred)

In [13]:
ac=accuracy_score(y_test,y_pred)

In [14]:
cm

array([[ 9,  0,  0],
       [ 0, 13,  1],
       [ 0,  0,  7]])

In [15]:
ac

0.9666666666666667